export const CONTACT_COUNTRY_ORDER = ['spain', 'usa', 'panama', 'canada']

const COUNTRY_LABELS = {
  spain: { es: 'España', en: 'Spain' },
  usa: { es: 'Estados Unidos', en: 'United States' },
  panama: { es: 'Panamá', en: 'Panama' },
  canada: { es: 'Canadá', en: 'Canada' },
}

export const CONTACT_LOCATIONS = [
  {
    id: 'hq',
    countryId: 'spain',
    name: { es: 'EXTINVAL HQ: Valencia', en: 'EXTINVAL HQ: Valencia' },
    city: { es: 'Valencia', en: 'Valencia' },
    locality: { es: 'Aldaia, Valencia', en: 'Aldaia, Valencia' },
    address: 'Carrer Serra d\'Espadà, 28, P. Ind. La LLoma\nAldaia, Valencia 46960, ES',
    phones: ['+34 96 367 40 53'],
    email: 'service@extinval.com',
    note: true,
    lat: 39.4607,
    lng: -0.4645,
  },
  {
    id: 'canarias',
    countryId: 'spain',
    name: { es: 'EXTINVAL Canarias', en: 'EXTINVAL Canary Islands' },
    city: { es: 'Las Palmas de Gran Canaria', en: 'Las Palmas de Gran Canaria' },
    locality: { es: 'Las Palmas de Gran Canaria', en: 'Las Palmas de Gran Canaria' },
    address: 'Calle de la Hoya del Rosario, 155, A\nLas Palmas de Gran Canaria, 35016, ES',
    phones: ['+34 656 908 793'],
    email: 'info@extinval-canaryislands.com',
    lat: 28.1248,
    lng: -15.43,
  },
  {
    id: 'almeria',
    countryId: 'spain',
    name: { es: 'EXTINVAL Almería', en: 'EXTINVAL Almeria' },
    city: { es: 'Almería', en: 'Almeria' },
    locality: { es: 'Almería', en: 'Almeria' },
    address: 'C. Carbón, 2, 04009 Almería, ES',
    phones: ['+34 629 156 781'],
    email: 'extinval-almeria@extinval.com',
    lat: 36.8381,
    lng: -2.4597,
  },
  {
    id: 'panama',
    countryId: 'panama',
    name: { es: 'EXTINVAL Panamá', en: 'EXTINVAL Panama' },
    city: { es: 'Panamá', en: 'Panama' },
    locality: { es: 'Panamá', en: 'Panama' },
    address: null,
    phones: ['507 600 709 31'],
    email: null,
    lat: 8.9936,
    lng: -79.5197,
  },
  {
    id: 'canada',
    countryId: 'canada',
    name: { es: 'EXTINVAL Canadá', en: 'EXTINVAL Canada' },
    city: { es: 'Canadá', en: 'Canada' },
    locality: { es: 'Canadá', en: 'Canada' },
    address: null,
    phones: ['507 600 709 31'],
    email: 'info@extinval-canada.com',
    lat: 43.6532,
    lng: -79.3832,
  },
  {
    id: 'usa-ca',
    countryId: 'usa',
    name: { es: 'EXTINVAL USA — California', en: 'EXTINVAL USA - California' },
    city: { es: 'California', en: 'California' },
    locality: { es: 'Alameda, California', en: 'Alameda, California' },
    address: '1721 Pearl St, Alameda\nCalifornia 94501, US',
    phones: ['+1 281 851 2886', '+1 305 804 2565'],
    email: 'r.pavia@extinvalusa.com',
    lat: 37.7799,
    lng: -122.2712,
  },
  {
    id: 'usa-la',
    countryId: 'usa',
    name: { es: 'EXTINVAL USA — Louisiana', en: 'EXTINVAL USA - Louisiana' },
    city: { es: 'Louisiana', en: 'Louisiana' },
    locality: { es: 'Saint Rose, Louisiana', en: 'Saint Rose, Louisiana' },
    address: '161 James Dr W, Saint Rose\nLouisiana 70087, US',
    phones: ['+1 281 851 2886', '+1 305 804 2565'],
    email: 'r.pavia@extinvalusa.com',
    lat: 29.9363,
    lng: -90.3154,
  },
  {
    id: 'usa-nj',
    countryId: 'usa',
    name: { es: 'EXTINVAL USA — New Jersey', en: 'EXTINVAL USA - New Jersey' },
    city: { es: 'New Jersey', en: 'New Jersey' },
    locality: { es: 'Harrison, New Jersey', en: 'Harrison, New Jersey' },
    address: '212 Davis Ave 1, Harrison\nNew Jersey 07029, US',
    phones: ['+1 281 851 2886', '+1 305 804 2565'],
    email: 'r.pavia@extinvalusa.com',
    lat: 40.7459,
    lng: -74.1551,
  },
]

export function getContactCountryLabel(countryId, lang = 'es') {
  return COUNTRY_LABELS[countryId]?.[lang] ?? COUNTRY_LABELS[countryId]?.es ?? countryId
}
